name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Ensure we can build the image
        run: docker build -t ferlabcrsj/maven-node  .

      - name: Push the frontend image on the docker registry
        uses: Ferlab-Ste-Justine/action-push-image@v2
        with:
          username: ${{ secrets.FERLAB_DOCKER_HUB_USER }}
          password: ${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}
          image: ferlabcrsj/maven-node